name: Lint

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.49
    - name: Build project
      run: go build
